### ISSUE TITLE
[tutorial] broken hello-solder example board

### ISSUE THREAD

**Issue by 5shekel** [boldport/pcbmode#29]
following the [guide ](http://pcbmode.readthedocs.io/en/latest/hello-solder.html)  
hello-solder project fails to build.

```
(pcbmode-env) user@Box:~/dev/pcbmode$ pcbmode -b hello-solder -m
-- Processing PCBmodE's configuration file
-- Processing board's configuration file
-- Creating board
Traceback (most recent call last):
  File "/home/yair/dev/pcbmode-env/bin/pcbmode", line 11, in <module>
    load_entry_point('pcbmode==4.1.dev34+ngabe96e3', 'console_scripts', 'pcbmode')()
  File "build/bdist.linux-x86_64/egg/pcbmode/pcbmode.py", line 387, in main
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/board.py", line 21, in __init__
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/module.py", line 58, in __init__
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/module.py", line 960, in _getComponents
AttributeError: 'list' object has no attribute 'get'
```

**Comment by JarrettR** [comment]
Same as issue #14 
I'm happy to update the doc to work for TheLady instead, as soon as my last PR gets accepted :)
