### ISSUE TITLE
KeyError: 'stroke-width'

### ISSUE THREAD

**Issue by KidIccurus** [boldport/pcbmode#36]
On attempting to generate gerbers for a modified version of "thelady" demo board, I get the following error:
`-- Processing PCBmodE's configuration file
-- Processing board's configuration file
-- Creating Gerbers
Traceback (most recent call last):
  File "/home/sam/pcbmode-env/bin/pcbmode", line 11, in <module>
    load_entry_point('pcbmode==4.1.dev41+ngba62f96', 'console_scripts', 'pcbmode')()
  File "build/bdist.linux-x86_64/egg/pcbmode/pcbmode.py", line 397, in main
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/gerber.py", line 81, in gerberise
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/gerber.py", line 194, in __init__
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/gerber.py", line 369, in _flattenCoords
KeyError: 'stroke-width'
`
The modification made to the board was to insert an object made with Inkscape's bezier curve tool to the top copper routing layer. The object is set with a solid fill and no stroke paint, store transforms is set to optimized and the object was moved after being created.

The commands I ran were:
`pcbmode -b thelady -e
pcbmode -b thelady --fab`

This installation has been used to succesfully compile an unmodified version of the "thelady" board.

Thanks in advance for your help.

**Comment by dnaito** [comment]
not sure if you fixed this, but I hit the same issue.  Turns out pcbmode uses both the json and the svg to generate the gerbers. Once you have made changes, you need to extract (-e), and make board (-m) before you fab the board.
