### ISSUE TITLE
Won't install on Windows anymore?

### ISSUE THREAD

**Issue by rahji** [boldport/pcbmode#37]
I had a working version on my Windows computer and I recall the setup being pretty simple. I updated from github and now I can't seem to get it installed. This is what I get...

```
PS C:\Users\robduarte\Documents\GitHub\pcbmode> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    zip_safe = True
  File "C:\Python27\lib\distutils\core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Python27\lib\site-packages\setuptools\dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "C:\Python27\lib\distutils\dist.py", line 287, in __init__
    self.finalize_options()
  File "C:\Python27\lib\site-packages\setuptools\dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "build\bdist.win-amd64\egg\setuptools_scm\integration.py", line 19, in version_keyword
  File "build\bdist.win-amd64\egg\setuptools_scm\__init__.py", line 104, in get_version
  File "build\bdist.win-amd64\egg\setuptools_scm\__init__.py", line 69, in _do_parse
  File "build\bdist.win-amd64\egg\setuptools_scm\__init__.py", line 30, in version_from_scm
  File "build\bdist.win-amd64\egg\setuptools_scm\__init__.py", line 36, in _version_from_entrypoint
  File "build\bdist.win-amd64\egg\setuptools_scm\git.py", line 11, in parse
  File "build\bdist.win-amd64\egg\setuptools_scm\utils.py", line 58, in do_ex
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by pgvoorhees** [comment]
Hi @rahji, pcbmode is using a ptyhon package which is trying to use GIT. 

Please install GIT: https://git-for-windows.github.io/ and make sure git.exe exists in the PATH environment variable. That should take care of this particular error.
